### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by greiginsydney** [dowlingrc/MeritorHX#1]
Hi @dowlingrc ,

I came to GitHub today to see if anyone's written a Nitsuko emulator, so I thought I'd hit paydirt when this repo was the sole match.

Did you get anywhere with it, or is it comfortably stalled at readme.md? If you have any info on the protocol or hardware you used, I'd be grateful if you could share it here.

(My desire is to drive what was known in the Australian market as the "Commander N" handset - N for Nitsuko - released here in the early 80s.)

Thanks,

\- G.

**Comment by dowlingrc** [comment]
Hi G.:
Comfortably stalled is a good way of putting it.  I have some Arduino code to drive the keypad board, but that's the only part of the whole handset I have.  I got it surplus somewhere, probably Radio Shack but maybe in Akihabara back in the day, and reverse-engineering the matrix schematic was an interesting exercise.
Sad to say I have no idea about the protocol used in the rest of the handset.
Cheers,
-- Bob (formerly an Ada guy)

**Comment by greiginsydney** [comment]
Hey Bob,

Ahhh, dang. I was hoping you might have been making an emulator to drive something like this 80s beauty (shown here without its Brady-Bunch-esque wood-grain face panel):

![image](https://github.com/dowlingrc/MeritorHX/assets/11004787/19d88c41-09c6-4f07-8eaf-0a1bd708a51e)

<br/>
The idea's been bubbling around in my head for a while, and I've recently applied power to the one above, but I've not been able to sniff any data (yet), so either my guessed test rig is incorrect, or it requires some initialisation first.

My next step is to find someone with a working one and sniff the data pair while it's powered.


\- Greig.
